baseURL: https://noborus.github.io/
languageCode: en-us
defaultContentLanguage: en
title: Noboru Saito's page
theme: hugo-theme-relearn
services:
  googleAnalytics:
    id: G-CGNLN23TRR

languages:
  en:
    languageName: "English"
    title: "Noboru Saito's page"
    weight: 1
    menu:
      shortcuts:
      - name: "<i class='fas fa-tags'></i> Tags"
        url: "/tags"
      - name: "<i class='fas fa-list'></i> Categories"
        url: "/categories"
  ja:
    languageName: "Japanese"
    title: "斉藤登のページ"
    weight: 2
    menu:
      shortcuts:
      - name: "<i class='fas fa-tags'></i> タグ"
        url: "/tags"
      - name: "<i class='fas fa-list'></i> カテゴリー"
        url: "/categories"
      - name: "qiita"
        url: "https://qiita.com/noborus"
module:
  mounts:
    - source: content
      target: content
      lang: 'ja'
    - source: content
      target: content
      lang: 'en'

outputs:
  home: ["HTML", "RSS"]

imaging:
  quality: 99

params:
  AuthorName: "Noboru Saito"
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  additionalContentLanguage:
    - "en"
    - "ja"
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: false
  search: true
  disableLandingPageButton: false
  themeVariant: 'custom1-variant'
  disableShortcutsTitle: true
  collapsibleMenu: true
  images:
    - '/images/logo.png'

markup:
  goldmark:
    renderer:
      unsafe: true
